### ISSUE TITLE
Renndaten übernehmen

### ISSUE THREAD

**Issue by svenflossmann** [RaceHorology/RaceHorology#131]
Möglichkeit, Renndaten übernehmen zu können.

Use-Case: Bei mehreren Rennen, die ähnliche Streckendaten haben

**Comment by mstenz** [comment]
Das könnte man so machen wie bei der Konfiguration mit Templates, und zwar dass man nur bestimmte Daten im Template speichert oder übernimmt. 
Also z.b. verschiedene Templates für Homoligierte Strecken oder das Feld für den Zeitnehmer. Die anderen Felder bleiben dann unangetastet.
