### ISSUE TITLE
Listentitel erscheint manchmal nicht

### ISSUE THREAD

**Issue by svenflossmann** [RaceHorology/RaceHorology#252]
Die Listenüberschriften (Startliste, 1. Lauf, Ergebnisliste ….) werden nur gedruckt, wenn in den Renndaten unter Beschreibung 2 Zeilen gefüllt sind.

**Comment by svenflossmann** [comment]
@BerndKlostermeyer Habe versucht dieses Problem nachzustellen. Habe es nicht geschafft. Ich habe für die Beschreibung eines Rennens diverse Varianten uasprobiert (gar nichts, eine Zeile, zwei Zeilen, ...) auf dem Ausdruck war immer alles korrekt. Der Listentitel erscheint aber in der 2. Zeile so wie im Screenshot:
![grafik](https://user-images.githubusercontent.com/50514116/143765745-fba9b1a8-b591-47f8-a11f-e291e6f2b9c9.png)

Ich mache das Issue zu. Wenn Du es nochmal reproduzieren kannst, schicke mir die passende Datendatei nochmal zu.

**Comment by BerndKlostermeyer** [comment]
@svenflossmann : Ich konnte es gerade reproduzieren: Es liegt an der Bewerbsanlage. Wenn der Bewerb in DSValpin angelegt wurde, erscheinen die Listentitel nur wie von mir beschrieben (2 Zeilen der Beschreibung). Wenn der Bewerb über RH angelegt wird funktioniert es auch ohne die Beschreibung. (V.0.4.6.41)

**Comment by BerndKlostermeyer** [comment]
Hi Sven,

bin noch da :). Etwas viel Arbeit @work momentan…

Irgendwas funktioniert hier nach wie vor nicht. Erst dachte ich, es lag an einem im DSValpin angelegten Bewerb, ist es aber auch nicht. Ich hatte einen in RH angelegt, der ging. Kann ich aber nichtmehr nachstellen.

Bei der anliegenden DB ist es so, wie von mir beschrieben.

VG
Bernd


Bernd Klostermeyer
Am Lehmkamp 7
31061 Alfeld (Leine)
Tel. (0 51 81) 2 67 47
Mobil (0160) 5 33 33 38
***@***.***

**Comment by BerndKlostermeyer** [comment]
Hall Bernd,

 

ja, auf dem PDF ist einedeutog zu sehen, dass da Murks raus kommt. Danke. Schaue ich mir an …

 

… hmm, bei mir geht’s. Strange.

 

Hast Du zufällig die Liste auf einem anderen Rechner gemacht, wenn es mal geht bzw. nicht geht?

 

Ich schaue nochmal den Code an und versuche zu finden, woran das liegen kann.

 

Melde mich.

 

VG Sven

**Comment by svenflossmann** [comment]
Konnte den Fehler nachvollziehen. Bei drei Zeilen in der Rennbeschreibung tritt der Fehler praktisch immer auf.
Grund ist eine zu kleine Box, in die der Header gerendert wird.
