### ISSUE TITLE
Speichern der Renn-Konfiguration in der Datenbank

### ISSUE THREAD

**Issue by svenflossmann** [RaceHorology/RaceHorology#293]
Aktuell wird die Rennkonfiguration als ein JSON File namens "*.config"-File neben der Datenbank gespeichert.

Um den parallelen Betrieb von RH und DSVALpin / DSVALpinX zu verbessern, wäre es besser, wenn die Konfiguration innerhalb der Datenbank gespeichert werden würde.

**Comment by mstenz** [comment]
ich fände es super wenn es eine sogenannte "global" config geben würde und dann eine Project/Race spezifische die die globale überschreibt. 
Ein Positiv-Beispiel wie Konfiguration super funktioniert sind z.b. die Produkte phpstorm oder ähnliches.
