### ISSUE TITLE
Feature: Import von Renndaten

### ISSUE THREAD

**Issue by mstenz** [RaceHorology/RaceHorology#310]
Es wäre gut wenn die Renndaten von anderen DB's übernommen werden könnten, "Import-Knopf"
Oft verwendet man für manche Felder die selben Daten, so geht die Erstellung eines Bewerbs schneller.

**Comment by mstenz** [comment]
Ich glaube ist ein Double: https://github.com/RaceHorology/RaceHorology/issues/138

**Comment by svenflossmann** [comment]
> Ich glaube ist ein Double: #138

In der Tat ... ich schließe daher mal.
