### ISSUE TITLE
Bug: mnuClose nicht enthalten

### ISSUE THREAD

**Issue by mstenz** [RaceHorology/RaceHorology#316]
Schliessen Funktion nicht implementiert

**Comment by svenflossmann** [comment]
@mstenz Was genau mienst Du hier?
mnuClose ist implementiert. Es fehlt aber "Quit" bzw. Programm beenden.
Meinst Du letzteres?

**Comment by mstenz** [comment]
Hab jetzt grad das Studio nicht offen, aber beim Click im Menü "Schliessen" passiert nichts, ich glaube die mnuClose function ist nicht implementiert.

**Comment by svenflossmann** [comment]
schließen schließt die Datei. Wenn keine offen ist, macht das natürlich nix.

Aber "Beenden" fehlt
