### ISSUE TITLE
Feature: Parallel-Disziplinen

### ISSUE THREAD

**Issue by mstenz** [RaceHorology/RaceHorology#331]
Parallel-Slalom in verschiedenen Arten und Systemen sind heute extrem beliebt. Habe Anfang Januar wieder einen. 
DSVAlpin-P existiert heute dafür. Evtl. lässt sich diese Funktion/Code zusammenfügen. 

Folgende Arten sind mir bekannt:

- Jeder Teilnehmer fährt einmal den roten und blauen Parcour. Beide Zeiten werden addiert
- Jeder Teilnehmer fährt einmal den roten und blauen Parcour, nur die beste Zeit wird gewertet
- Baumsystem
- Baumsystem, derjenige mit der schnellsten Zeit aus dem Vordurchgang kann Parcour wählen. 
- Qualifikation für Baumsystem (wird meist als seperates Rennen durchgeführt)
- Es zählt die Differenzzeit und nicht die Gesamtlaufzeit (Variante für alle Möglichkeiten)

Diese Disziplin kann mit einem Zeitnahmegerät oder mit 2 seperaten Zeitnahmegeräten durchgeführt werden (je nach Art und Anforderung). Bei 2 Zeitnahmegeräten müsste man mit  Classement Zeiten nachschieben. Alternativ mit 2 COM-Ports.

**Comment by mstenz** [comment]
Here the ALGE code example for PSL (netto time):
```
 0002rC0  21:03:43.8352 02    <-- Startnummer 1 auf blauem (linkem) Kurs gestartet
 0001bC3  21:03:43.8352 02    <-- Startnummer 2 auf rotem (rechtem) Kurs gestartet
 0001bC0M 21:10:17.7300 02    <-- Startnummer 1 ist im Ziel (hier Manuell simuliert)
 0001bRTM 00:06:33.894  02    <-- Laufzeit von Startnummer 1
 0002rC1M 21:10:18.4200 02    <-- Startnummer 2 ist im Ziel (hier Manuell simuliert)
 0002rRTM 00:06:34.584  02    <-- Laufzeit von Startnummer 2
 0001bDTR 00:00:00.690  02    <-- Blau war schneller um 69 hundertstel
```

**Comment by svenflossmann** [comment]
Habe Parallelslalom eingebaut für Zeitmessung (kein K.O. System)
Für KO System wären die Änderungen deutlich größer, auch vom Workflow here. Das werde ich auf absehbare Zeit nicht einbauen.

Unterstütze Modi:
- Jeder Teilnehmer fährt einmal den roten und blauen Parcour. Beide Zeiten werden addiert
- Jeder Teilnehmer fährt einmal den roten und blauen Parcour, nur die beste Zeit wird gewertet

Unterstütztes Zeitmessgerät: ALGE TdC 8000/8001

Daher sehe ich diesen Issue erstmal als geschlossen an.
