### ISSUE TITLE
Bug: Handzeitimport während aktiver Zeitnahme (Exception) bei gleichem Port

### ISSUE THREAD

**Issue by mstenz** [RaceHorology/RaceHorology#337]
Wird die Handzeit vom selben Port geladen wie gerade bei der aktiven Zeitnahme benutzt wird, kommt es zur Exception
https://github.com/RaceHorology/RaceHorology/blob/5d495f52da3e8071705265dd34f9a94bc3fdfa9e/RaceHorology/HandTimingUC.xaml.cs#L166
Ich denke es sollte eine Meldung kommen dass der Port gerade genutzt wird und dafür die Zeitnahme unterbrochen werden muss, evtl. mit nachfrage ob dies getan werden soll. 

Konkrete Situation zum Nachstellen:
- ALGE TdC 8000/8001 nutzt COM 4
- Handzeit (e.g. Timy) wird am selben Port (COM 4) temporär angesteckt.

Es ist nicht möglich die Handzeit zu laden, da RH den COM-Port (COM 4) zur ALGE offen hält.

Lösungsmöglichkeiten:
- COM Port nur offen halten während Zeitmessung online geschaltet ist
- ALGE Verbindung trennen

**Comment by svenflossmann** [comment]
Ich habe ein Verbinden/Trennen des Zeitmessgerätes eingabeut (Statusleiste unten rechts). Damit müsste dieser Issue hier gelöst sein.
