### ISSUE TITLE
Handzeit empfangen nicht möglich wenn ALGE selben COM Port nutzt wie Timy

### ISSUE THREAD

**Issue by svenflossmann** [RaceHorology/RaceHorology#340]
Situation: ALGE TdC 8000/8001 nutzt COM 4
Handzeit (e.g. Timy) wird am selben Port temporär angesteckt.

Es ist nicht möglich die Handzeit zu laden, da RH den COM Port zur ALGE offen hält.

Lösungsmöglichkeiten: 
- COM Port nur offen halten während Zeitmessung online geschaltet ist
- ALGE Verbindung trennen

**Comment by mstenz** [comment]
same as #337
