### ISSUE TITLE
Gelöschter Teilnehmer erscheint in Rennergebnis, nicht aber in den anderen "Reports"

### ISSUE THREAD

**Issue by mstenz** [RaceHorology/RaceHorology#341]
Habe einen Teilnehmer hinzugefügt, dieser hat keinerlei Zeiten oder ähnliches, und dann gleich gelöscht. 
Er bleibt aber im Rennergebnis enthalten ohne die Möglichkeit mehr irgendwas mit dem Datensatz zu tun. 
Wenn er jetzt eine Zeit hätte würde ich das vorgehen verstehen, aber man muss es ja trotzdem entfernen können. Evtl. mit einer Abfrage beim Löschen von Teilnehmer wenn er bereits Zeiten/Daten hat ob das so korrekt ist?
![grafik](https://user-images.githubusercontent.com/7984329/147888529-44d7eee3-8f31-4f2a-b744-4663a90e673b.png)
Es handelt sich um "BALLE Henry" aus dem Screenshot

**Comment by mstenz** [comment]
Ich sehe gerade in der Startliste war er auch noch enthalten, da ich eine Startnummer vergeben hatte, ein Löschen aus der Startliste und Speichern löscht ihn aber auch nicht aus dem Rennergebnis.

**Comment by mstenz** [comment]
Erneutes öffnen der Datenbank behebt den Fehler

**Comment by svenflossmann** [comment]
Hängt mit #223 zusammen.
