### ISSUE TITLE
Feature: Eine "gesperrte" Startnummer kann trotzdem vergeben werden

### ISSUE THREAD

**Issue by mstenz** [RaceHorology/RaceHorology#342]
Es wurde eine Startnummer  unter "Nicht zu vergebene Startnummern" hinzugefügt. Diese wurde bei der manuellen Startnummernzuweisung trotzdem vergeben. 
Evtl. sollte man eine Meldung einblenden dass diese Startnummer nicht vergeben werden kann und dann abbrechen

**Comment by svenflossmann** [comment]
Bei einer manuellen Zuweisung würde ich davon absehen. Der Ausloser sollte wissen, was er tut.

deswegen ist das Feld auch auf der linken Seite im Bereich für automatische Auslosung.
