### ISSUE TITLE
Rennmeldung Livetiming - RaceHorology stürzt beim Aktivieren bei vielen Startern ab

### ISSUE THREAD

**Issue by BerndKlostermeyer** [RaceHorology/RaceHorology#346]
V.0.4.6.75 Rennen in Olang/ITA: ab ca. 70 Starten kein Aktivieren das Rennmeldung-Livetimings möglich. Login funktioniert, beim starten von Livetiming stürzt Programm ab. Internetverbindung via Mobilfunk-Hotspot über LTE oder sehr schwaches öffentliches Siigebiets-WLAN.

ggf. liegt es auch an den „Doppelbewerben“ von Rennmeldung. (2 DSV-Bewerbsnummern auf einem Rennmeldung-Bewerb). Schüler (ca. 65 Starter) haben noch funktioniert, Erwachsene nicht (ca. 80 Starter). Beim Einzelrennen mit 80 Startern hat es aber auch nicht funktioniert.

**Comment by BerndKlostermeyer** [comment]
muss an der Anzahl der Starter liegen - zu Hause mit dicker Leitung selber Fehler

**Comment by svenflossmann** [comment]
Nach Analyse mit @BerndKlostermeyer : Die Teilnehmer haben keine Klasse/Gruppe zugewiesen und das LiveTiming kommt damit nicht zurecht.

ToDo:

- [ ] Fix Livetiming
- [ ] Andere potentielle Stellen suchen, die auch betroffen sein können.

**Comment by svenflossmann** [comment]
@BerndMichael: Nachdem der Crash bei Dir heute auch aufgetreten ist, habe ich das gefixt. (Version > 0.4.7.35).
