### ISSUE TITLE
BUG: Export Ergebnis-.xml für DSV fehlerhaft

### ISSUE THREAD

**Issue by BerndKlostermeyer** [RaceHorology/RaceHorology#350]
Feedback von Christian Scholz/DSV:`

> _Die XML-Datei von Race-Horology lässt sich bei uns nicht einlesen, weil in der Datei die Rennnummer und die Aufschläge (calculated und applied, Mädchen und Buben) fehlen._

**Comment by svenflossmann** [comment]
Also duplicate of #144
