### ISSUE TITLE
Ausscheidungen lassen sich nicht zurücknehmen

### ISSUE THREAD

**Issue by mstenz** [RaceHorology/RaceHorology#360]
Wird ein Teilnehmer einmal mit NiZ, NaS oder DIS markiert kann man diese Entscheidung nicht mehr zurücknehmen. 
Man kann nur noch zwischen einer anderen Ausscheidung wechseln. 
Wenn man fälschlicherweise einen falschen Teilnehmer ausgeschieden hat oder eine Entscheidung sich aufgrund eines Einspruchs verändert wäre in diesem Zustand das Projekt verloren und der Benutzer müsste von vorne anfangen (oder die Datenbank manuell bearbeiten)

**Comment by svenflossmann** [comment]
Auf der Tab Ausscheidung kann man eine Ausscheidung zurücknehmen. einfach Startnummer eingeben und "keine Ausscheidung" is wählen.
