### ISSUE TITLE
Feature: Export nach CSV oder Excel sollte Totalzeit enthalten

### ISSUE THREAD

**Issue by Tilo70** [RaceHorology/RaceHorology#381]
**Ist der Featurewunsch relevant für ein bestimmtes Problem? Bitte beschreibe dies.**
Für die weitere Auswertung mit Excel wird auch die Totalzeit in Abhängigkeit von der Rennkonfiguration (Summe, Best of 2 usw.) UND eventuellen Disqualifikationen benötigt. Daraus kann dann die Platzierung innerhalb der jeweiligen Klasse abgeleitet werden.

**Beschreibe die Lösung die Du gerne hättest**
Export nach CSV oder Excel sollte Spalte Totalzeit enthalten (und zusätzlich eventuell die Platzierung innerhalb der Klasse)

**Beschreibe Alternativen, die es gäbe**
In Excel in Abhängigkeit von der Rennkonfiguration (Summe, Best of 2 usw.) die Läufe addieren bzw. Bestzeit ermitteln UND eventuelle Disqualifizierungen berücksichtigen.

**Weitere Informationen**

**Comment by svenflossmann** [comment]
Danke @Tilo70 für den Request.
Ich denke, dass macht Sinn ...
