### ISSUE TITLE
Rennmeldung.de benötigt DSVAlpinX Lizenz

### ISSUE THREAD

**Issue by svenflossmann** [RaceHorology/RaceHorology#388]
Aktuell benötigt Race Horology für das Livetiming von Rennmeldung.de eine DSVAlpinX Lizenz.
Diese muss im Unterdner "3rdParty" von Race Horology liegen.

**Comment by mstenz** [comment]
Wieso das? Bezahlt man für rennmeldung.de nicht schon für das Livetiming pro Bewerb?

**Comment by svenflossmann** [comment]
> Wieso das? Bezahlt man für rennmeldung.de nicht schon für das Livetiming pro Bewerb?

Historisch bedingt ... kommt ja weg.

**Comment by mstenz** [comment]
Ist das jetzt schon so und meinst du ich sollte das in die Dokumentation aufnehmen oder wie schnell "kommt das weg"?

**Comment by svenflossmann** [comment]
> Ist das jetzt schon so und meinst du ich sollte das in die Dokumentation aufnehmen oder wie schnell "kommt das weg"?

Das ist derzeit so und wird morgen wahrscheinlich nicht mehr so sein ...
