### ISSUE TITLE
Sprecheransicht geht mit iPad / iPhone nicht

### ISSUE THREAD

**Issue by svenflossmann** [RaceHorology/RaceHorology#397]
Die Sprecheransicht ist mit einem Mac-Browser (egal ob Safari, Chrome, ...) nur halb funktional.

Insbesondere gehen Updates in der Live-Ansicht nicht.

**Comment by svenflossmann** [comment]
Es sieht so aus, als ob neuere Safari Browser betroffen sind (siehe [hier](https://bugs.webkit.org/show_bug.cgi?id=228296))

Es gibt ein **_Workaround_** für betroffene Geräte. Er besteht darin, das experimentelle Feature "NSURLSession WebSocket" zu deaktivieren.

Um dies zu tun, muss man:

1. Navigate to: Settings > Safari > Advanced > Experimental Features
2. Set "NSURLSession WebSocket" to OFF and restart Safari (or the phone/tablet).

**Comment by dbrodkor** [comment]
Getestet am 8.12.2022 mit ipad, iPadOS 16.1.1, Safari Einstellungen mit NSURLSessionWebSocket auf "ON" gesetzt - das Display Update hat funktioniert wie gewünscht: gestartete Athleten, sowie Athleten mit Zielzeit werden angezeigt wie erwartet. Ich denke, dass sich das erledigt hat.

**Comment by mstenz** [comment]
@dbrodkor Vielen Dank fürs Testen :)

**Comment by mstenz** [comment]
Die Dokumentation wurde angepasst.
