### ISSUE TITLE
Startnummernzuweisung mit Auswahl der einzelnen Klasse fehlerhaft

### ISSUE THREAD

**Issue by mstenz** [RaceHorology/RaceHorology#410]
**Fehlerbeschreibung**
Sollte es mehrere Klassen geben und die Reihenfolge der Startnummernvergabe nicht exakt der Reihenfolge der Klassen in der DB entsprechen (nach id), so wird die Auswahl ignoriert und trotzdem die Reihenfolge in der Datenbank benutzt. 
Beispiel:
![grafik](https://user-images.githubusercontent.com/7984329/153529456-0b171eec-8c76-4a43-9a80-a302567089a4.png)
Ich möchte zuerst Jugend weiblich, danach Jugend männlich losen (oder alternativ erst Jugend männlich, danach Herren). 
Das funktioniert jedoch nicht.

**Comment by svenflossmann** [comment]
Doch, das müsste funktionieren. Hast Du mit Drag & Drop die Klassenreihenfolge verschoben?
... oder ich verstehe das Problem nicht.

Die id zählt übrigens nicht als Reihenfolge, das geht über die "sortpos" (die durch Drag&Drop" verändert wird.

**Comment by mstenz** [comment]
ich mach dir ein Beispielvideo zum nachstellen, augenblick

**Comment by mstenz** [comment]
> Hast Du mit Drag & Drop die Klassenreihenfolge verschoben?

Nein. Testweise in der Reihenfolge angelegt wie es in der DB oben vom Beispielbild ist. 

https://youtu.be/7APoueleAso

**Comment by svenflossmann** [comment]
Kommentar aus Bug #418 (@BerndKlostermeyer)

> Egal was bei der Startnummernvergabe als nächste Gruppe gewählt ist: es werden immer Startnummern für die erste bzw. nächste eingegebene Gruppe der Klassen und Gruppen-Eingabe vergeben.
> 
> Workarround: die Klassen lassen sich per drag & drop in die gewünschte Reihenfolge verschieben.
