### ISSUE TITLE
Export der Rangliste in Excel enthält keine Platzierung / Rang

### ISSUE THREAD

**Issue by MaikRud** [RaceHorology/RaceHorology#411]
Exportiert man die Rangliste so fehlt leider die Platzierung. Möchte man nun aus dem Excel über Serienbrief seine Urkunden drucken so fehlt dieses Feld eindeutig.

Sinnvoll wäre m.E. nach das zumindestens die angezeigte Gesamtplazierung mit exportiert wird, so wie man es sieht (gruppiert hat).

**Comment by svenflossmann** [comment]
Hallo @MaikRud  - ja, das macht Sinn.
