### ISSUE TITLE
Teilnehmer ändern Formular übernimmt nicht alle Felder in Teilnehmer

### ISSUE THREAD

**Issue by MaikRud** [RaceHorology/RaceHorology#412]
Wenn man über die Punktlisten arbeitet ist dies sicherlich kein so großes Problem. Bei einem kleineren Vereinsbewerb müssen ja die teilnehmer importiert oder eingegeben werden. Hier ist mir folgendes Verhalten aufgefallen.

Startpunkt: _Teilnehmer & Globale Konfiguration_, _Reiter Teilnehmer_

Jetzt klick: _Teilnehmer hinzufügen_
Neuen Eintrag in Liste suchen und zur Bearbeitung rechtsseitig die Daten bei Teilnehmer ändern eingeben.
Werden hier Einträge in den Feldern **Verein** sowie **Jahrgang** gemacht, so erscheinen diese nach Klick auf _Speichern_ nicht in der Teilnehmerliste. Ebenso verschwinden die Einträge bei _Teilnehmer ändern_.

Wünschenswert wäre hier ggf. auch eine Vorsortierung/Filterung des DropDown Feldes Klasse. Hier werden richtigerweise immer alle Klassen angezeigt. Eine automatische Zuweisung erfolgt nicht. Aber wenn die Kategorie und der Jahrgang "plausibel" sind, könnte dieses Feld (ggf. mit Warnhinweis bei Änderung) automatisch schon gesetzt werden.

**Comment by mstenz** [comment]
@svenflossmann  Gerade auch ein Rennen angelegt ohne DSV Liste, dass der Jahrgang und der Verein nicht übernommen werden und man so jeden Teilnehmer 2 mal bearbeiten muss ist wirklich nervig. Ist das evtl. ein leichter Fix?

**Comment by svenflossmann** [comment]
Habe die Issues gefixt.

Bei der Combobox mit der Klasse ist das etwas schwieriger zu fixen. Hier habe ich es erstmal so gemacht, dass wenn keine Klasse manuell ausgewählt wurde / ist, die passende Default-Klasse automatisch beim Speichern zugewiesen wird.

**Comment by MaikRud** [comment]
Hallo und guten Morgen,

super und sehr gut, bin auf die neue Version gespannt. Bin am kommenden Sonntag mit in Zwiesel, sie auch?

Viele Grüße Maik Rudolph 

Am 11. September 2022 16:58:06 MESZ schrieb Sven Flossmann ***@***.***>:
