### ISSUE TITLE
Ergebnisliste falscher Eintrag Timing/Zeitmessgerät

### ISSUE THREAD

**Issue by MaikRud** [RaceHorology/RaceHorology#413]
Ich hatte am Wochenende einen kleinen Vereinsinternen Wettbewerb. Durch räumliche Gegebenheiten war keine Übertragung der Zeiten mittels Kabel möglich. Weiterhin wurde keine Alge TdC8000 eingesetzt.

Wie verwundert war ich, dass auf der Ergebnisliste, unten rechts, bei Timing dieses aber stand. Die Auswahl des Zeitmessgerätes (Einstellungen -> Zeitmessgerät) waren "leer".

![grafik](https://user-images.githubusercontent.com/99465303/153547644-bd431558-a92d-4815-9b5c-6ae834fe49d6.png)

Auf der Ergebnisliste erschien jedoch der TdC8000/8001.
 
![grafik](https://user-images.githubusercontent.com/99465303/153547692-03c62b1f-56aa-42d8-a3bf-1489fe1d0e6a.png)

Lösungsidee, diesen Eintrag auf der Ergebnisliste entweder freilassen, oder aber ein Freitextfeld definieren über das man seine Eingaben für die Ergebnisliste hinterlegen kann. Dieses wird dann verwendet wenn man kein Zeitmessgerät in den Einstellungen definiert hat.

**Comment by svenflossmann** [comment]
Ja, das stimmt. Der Ausdruck enthält momentan einen statischen Text. Das muss natürlich geändert werden.

**Comment by svenflossmann** [comment]
Punkt wird wichtiger, da jetzt mehr als 3 Geräte unterstützt werden. => diese Saison.
