### ISSUE TITLE
BUG: Startnummernvergabe Auswahl „nächste Gruppe“ funktionslos

### ISSUE THREAD

**Issue by BerndKlostermeyer** [RaceHorology/RaceHorology#418]
egal was bei der Startnummernvergabe als nächste Gruppe gewählt ist: es werden immer Startnummern für die erste bzw. nächste eingegebene Gruppe der Klassen und Gruppen-Eingabe vergeben.

Workarround: die Klassen lassen sich per drag & drop in die gewünschte Reihenfolge verschieben.

**Comment by mstenz** [comment]
duplicate mit #410

**Comment by BerndKlostermeyer** [comment]
Oh 😬. Bitte schließen
