### ISSUE TITLE
Punkteberechnung rundet falsch

### ISSUE THREAD

**Issue by svenflossmann** [RaceHorology/RaceHorology#438]
Siehe Screenshot. Hier sollte 17.93 rauskommen.
![grafik](https://user-images.githubusercontent.com/50514116/160996081-c322553c-5fc6-48e4-bffb-e55e69e1866d.png)

**Comment by mstenz** [comment]
Es wäre toll wenn der Mindestzuschlag auch noch in einer Zeile steht, womit man dann nachvollziehen kann dass jetzt der Mindestzuschlag angweandt worden ist.

**Comment by svenflossmann** [comment]
Gefixte Version:
![grafik](https://user-images.githubusercontent.com/50514116/161139606-2e4be28e-78e0-4574-8331-3d8e173000fa.png)

Weiterhin: Zeilen die nicht beitragen werden weggelassen (Adder oder Z-Wert gleich 0).
