### ISSUE TITLE
Alpenhunde - Download aller Zeitstempel

### ISSUE THREAD

**Issue by svenflossmann** [RaceHorology/RaceHorology#478]
Ähnlich dem Classment Empfang soll auch mit dem Alpenhunde-System ein Download aller Zeitstempel möglich sein.

**Comment by svenflossmann** [comment]
@Alpenhunde Christian, kannst Du mir hier nochmal die URLs sagen, mit denen ich die Zeitstempel runterladen kann?

**Comment by Alpenhunde** [comment]
alle Events  kann  man  mit:
http://192.168.4.1/timing/results/?action=all_events
abholen
