### ISSUE TITLE
Alpenhunde CSV Export

### ISSUE THREAD

**Issue by svenflossmann** [RaceHorology/RaceHorology#479]
Für den Starter gibt es die möglichkeit die Startliste via CSV File zu importieren.

Dieses CSV Format soll unterstützt werden.

**Comment by svenflossmann** [comment]
@Alpenhunde Kannst Du bitte noch das CSV-Format angeben. Danke.

**Comment by Alpenhunde** [comment]
[Alpenhunde_Team_Format.csv](https://github.com/RaceHorology/RaceHorology/files/9896951/Alpenhunde_Team_Format.csv)

Encoding ist  Unicode (UTF-8)

Short  Name sind max. 5 Zeichen, keine Umlaute, keine Sonderzeichen
Erlaubte Zeichen sind :    .   ,   !   ?   -   +    *   _   =    :    (    )   @    / 

Die erste Zeile kann entweder genau die Bezeichnungen haben wie die Beispieldatei, dann wird sie nicht importiert.
Oder die erste Zeile enthält gleich einen gültigen Eintrag, dann wird sie importiert.
