### ISSUE TITLE
Feature: Verbesserung Zeitnahme Start und Stop button

### ISSUE THREAD

**Issue by mstenz** [RaceHorology/RaceHorology#481]
aktuell gibt es einen seperaten Start und einen seperaten Stopknopf. 

Dies kann verwirrend sein weil es aktuell verschiedene Stati gibt (Knöpfe deaktiviert, mit farbe hinterlegt usw.). 

Es wäre einfacher wenn nur ein Knopf existiert, der Farbe und inhalt wechseln kann je nach Status.

**Comment by svenflossmann** [comment]
Nachdem sich viele schon an die aktuelle Buttons gewöhnt haben, und es mitlerweile im zentralen Statusbereich oben ein eindeutigen Status gibt, wenn die Zeitnahme nicht aktiv ist, schließe ich dieses Issue.

**Comment by mstenz** [comment]
ich glaube das hab ich sogar letztes Jahr schon implementiert, nur noch nicht "eingereicht". Ich schau mal nach.
