### ISSUE TITLE
Feature: "Teilnehmer melden/abmelden" Button 

### ISSUE THREAD

**Issue by mstenz** [RaceHorology/RaceHorology#494]
Aktuell muss man jeden Teilnehmer aufwendig zum Rennen X melden (Checkbox) 

Bei vielen Teilnehmern dauert das zu lange. Es wäre schön wenn es einen Button gibt (bzw. 2) der die ausgewählen Teilnehmer meldet bzw. abmeldet. 

Da es theoretisch aktuell mehrere Disziplinen geben kann müsste man aktuell das für alle Rennen übernehmen (sehe das aber unkritisch weil eigentlich niemand aktiv mehrere Rennen pro Datei macht) oder eine Auswahlbox in einem popup abfragen für welches Rennen gemeldet werden soll. 

https://github.com/RaceHorology/RaceHorology/issues/417

**Comment by mstenz** [comment]
https://github.com/RaceHorology/RaceHorology/issues/417

**Comment by svenflossmann** [comment]
Du kannst mehrere Teilnehmer gleichzeitig auswählen und alle zu einem Rennen hinzufügen oder abwählen.
Dazu die Teilnehmer markieren, danach in dem rechten Teil des Bildschirms auf _Teilnehmer_ gehen und die entsprechenden Checkboxen verändern und _Speichern_ drücken.

**Comment by mstenz** [comment]
Das ist ein guter Hinweis, diese Funktion ist aktuell so noch nicht dokumentiert. Werde das seperat in der Doku eintragen. 

Ein seperat Button für An-/abmelden wäre trotzdem sinnvoll, allerdings später wenn die Funktion aus #496 umgesetzt sind.
