### ISSUE TITLE
Feature: Sortierung der Tabellen innerhalb "Klassen und Gruppen"

### ISSUE THREAD

**Issue by mstenz** [RaceHorology/RaceHorology#513]
Aktuell ist keine Sortieren der Tabelle möglich über die Überschriften.

**Comment by svenflossmann** [comment]
Meinst Du die Tabellen für das Konfigurieren/Eingeben der Klassen und Gruppen?

Falls ja: Das ist Absicht, da die Sortierreihenfolge der Klassen und Gruppen die Reihenfolge der Ergebnislisten vorgibt.
