### ISSUE TITLE
Ersatzzeit schreibt kein Laufzeitwert in DB, Folge: DSVAlpinX nimmt eine 0-Zeit an

### ISSUE THREAD

**Issue by svenflossmann** [RaceHorology/RaceHorology#531]
Wenn eine Ersatz (Start oder Ziel) berechnet wird, wird die Laufzeit aus der DB gelöscht.
RH erzeugt korrekte Listen usw.

Aber DSVAlpinX (vermutlich aus DSVAlpin) nehmen die Zeit 0:00 an, was zu einer falschen Ergebnisliste oder Urkundenliste führt.

**Comment by mstenz** [comment]
Dies hat ebenfalls auswirken auf aktuell laufende Livetimings (z,.b. das Livetiming von race-engine, dass die Werte direkt aus der DB liest)
