### ISSUE TITLE
Auslosung bei Auslosungszahl höher 15 - Startlisten werden falsch generiert/angezeigt

### ISSUE THREAD

**Issue by SusanneHoll** [RaceHorology/RaceHorology#624]
Auslosung bei DSC U14 nach Klassen
JG 2011 weiblich - ganze Klasse wird gelost, Auslosungszahl 100 wurde eingegeben
JG 2010 weiblich - Auslosungszahl 15
dto. JG 2011 und 2010 männlich

Die Auslosung an sich findet korrekt statt, JG 2011 wird komplett gelost, JG 2010 die ersten 15.

Jedoch ist die Darstellung der Startliste nicht korrekt, die Startnummern werden im Jahrgang 2011 durcheinandergewürfelt.

Lost man gleichermaßen in DSVAlpin aus und öffnet dann die Datenbank in RaceHorology, ist die Darstellung/Reihenfolge korrekt!

[Startliste DSC falsche Darstellung bei Auslosung in race horology.pdf](https://github.com/RaceHorology/RaceHorology/files/14116934/Startliste.DSC.falsche.Darstellung.bei.Auslosung.in.race.horology.pdf)

**Comment by mstenz** [comment]
Die Vorgehensweise ist folgend: Konfiguration für normale Auslosung. Dann Losung. Nach der Losung muss die Einstellung auf "Startnummer(Aufsteigend)" geändert werden.

**Comment by SusanneHoll** [comment]
Verstehe ich nicht. Bei der Auslosung steht Richtung - aufsteigend. Dann lose ich wie oben beschrieben. Speichern. Startliste aktualisieren. Reihenfolge der Startnummern stimmt nicht. Gibt es eine zusätzliche Einstellung auf Startnummer aufsteigend, die ich nicht finde?

**Comment by SusanneHoll** [comment]
Habe mir das Ganze nochmals angeschaut. Wie gesagt, die Auslosung bei den JG 2011 erfolgt korrekt über die ganze Gruppe. Im Bereich der ausgelosten Teilnehmer (Liste im oberen Bereich bei Auslosung, Vorläufige Startliste) sind die Startnummern auch richtig sortiert. Bei der Anzeige Live Listen als auch Berichte drucken stimmt die Darstellung nicht. Hier wird ab der 16. Startnummer nicht nach Startnummer sortiert, sondern nach DSV-Punkten (aufsteigend). Deshalb stimmt die Reihenfolge der Startnummern nicht.
Ist hier ein Automatismus bezüglich der DSV-Punkte hinterlegt, damit Nachmeldungen richtig einsortiert werden? Dies wäre in unserem Fall kontraproduktiv.

**Comment by mstenz** [comment]
Wichtig ist der Punkt "Startnummer aufsteigend" einzustellen nach dem Losen. Achtung: Es gibt eine Lokale und eine Globale Rennkonfiguration. Wenn du es in der Globalen umstellst, aber die Lokale angewandt wird dann ändert sich die Liste nicht. Am besten alle einstellungen bei der Globalen Konfiguration vornehmen und bei der Lokalen konfiguration den Button "Global Konfiguration nutzen" drücken. Ich habe selbst schon einige U16/U14 rennen so gemacht, bei mir hat das einwandfrei funktioniert.

**Comment by SusanneHoll** [comment]
Okay, da lag wohl der Fehler. Habe die Einstellung bei der globalen Konfiguration geändert und dann hat es geklappt. Danke!
