### ISSUE TITLE
Daten-Export an DSV klappt nicht aufgrund Fehlermeldung "DSV-Punkteliste ist unbekannt"

### ISSUE THREAD

**Issue by SusanneHoll** [RaceHorology/RaceHorology#625]
Beim Versuch die zip-Datei für den DSV-Export zu erstellen kommt folgende Fehlermeldung:

"Verwendete DSV-Punkte-Liste ist unbekannt"

Die eingelesene Punkteliste wurde von Rennmeldung.de mit der Datenbank geliefert und hat die übliche Bezeichnung und das übliche Format (siehe Anlage).

Kann der Fehler daran liegen, dass zwischen Übernahme der Daten von Rennmeldung und der Rennauswertung ein Windows-Update auf dem Rechner gefahren wurde?

[DSVSA2404.txt](https://github.com/RaceHorology/RaceHorology/files/14116987/DSVSA2404.txt)

**Comment by mstenz** [comment]
Dies liegt daran, dass die DSV-Liste nicht importiert ist. Einfach die jeweilige Liste importieren (entweder online, oder über die .txt-Datei), dann verschwindet der Fehler. Rennmeldung schreibt zwar die Punkte mit in die Datenbank, aber diese wird von RH noch überprüft.

**Comment by SusanneHoll** [comment]
Die DSV-Liste ist/wurde importiert, Teilnehmer wurden hinzugefügt. Export DSV wie oben beschrieben nicht möglich.

**Comment by mstenz** [comment]
Kannst du bitte noch auf den Button "Punkte aller Teilnehmer aktualisieren" drücken. Dann sollte es denke ich gehen.

**Comment by SusanneHoll** [comment]
Passt. Nach der Aktualisierung der Teilnehmer hat der Export funktioniert. Danke!
