### ISSUE TITLE
Konfiguration Bewerb, Übernahme der Werte (F-Wert, Zuschlag etc.)

### ISSUE THREAD

**Issue by SusanneHoll** [RaceHorology/RaceHorology#626]
Möchte man die entsprechenden Werte für ein Template automatisch einlesen, muss man den button "Zurücksetzen" verwenden.

Diese Bezeichnung ist für den Anwender sehr irreführend, bezeichnet doch ein Zurücksetzen eher ein Löschen von Werten und nicht ein Einfügen.

Hier wäre eine andere Bezeichnung, z. B. "Übernehmen" oder "Einlesen" hilfreicher.

**Comment by mstenz** [comment]
Zurücksetzen löscht das Formular. Bei der Auswahl des Templates werden die Werte direkt geschrieben. Mit speichern werden diese dann übernommen. Ich habe es gerade auch nochmal getestet mit der aktuellsten Version. 
Falls es bei dir anders funktioniert, kannst du bitte beschreiben wie du genau vorgehst?

**Comment by SusanneHoll** [comment]
Okay. Wenn man den Bewerb nicht in Race Horology anlegt, muss man das Template nochmals aufrufen, dann klappt das - aber nicht immer. Wenn man das Template ändert, werden die Werte unten nicht immer angepasst. Aber da muss man dann halt selbst noch ein Auge draufhaben, da z.B. der Mindestzuschlag bei U14/U16 beim DSC = 0. Danke!

**Comment by mstenz** [comment]
Verstehe, nachdem ja DSV Alpin eh auf längere Zeit gesehen nicht mehr benötigt wird, scheint das ein temporäres Problem zu sein. Ich schliesse den Issue daher. 
Solange die Einstellungen stimmen, ist es nicht erforderlich mit einem Template die Werte zu überschreiben. Ich selbst lege alle Bewerbe direkt in RaceHorology an. DSV Alpin verwende ich aktuell nur bei Mannschaftswertung oder spezialAusgaben die es noch nicht in RaceHorology gibt. Da die Datei aber kompatibel ist funktioniert das öffnen auch in DSValpin wenn die Datei in RH angelegt wird.
