### ISSUE TITLE
Live Listen - Teilnehmer INAKTIV

### ISSUE THREAD

**Issue by SusanneHoll** [RaceHorology/RaceHorology#627]
Die Auswahl Teilnehmer bei den Live Listen ist inaktiv.

Startlisten und Ergebnislisten lassen sich (auch ohne Startnummern oder Ergebnisse!) generieren, eine Teilnehmerliste jedoch nicht.

Wünschenswert wäre hier auch die Möglichkeit einer Darstellung der Teilnehmer nach Verband/Region (beim DSC unabdingbar, da bei der MaFü immer nochmals die Teilnehmer von den Mannschaftsführern kontrolliert werden).

**Comment by mstenz** [comment]
#614

**Comment by mstenz** [comment]
#281
